version: '3.7'

services:
  webrtc-front:
    build:
      context: .
      dockerfile: front/dockerfile
    ports:
      - 3000:3000
    volumes:
      - /home/ubuntu/app/front/build:/home/ubuntu/app/front/build
  
  webrtc-server:
    build: 
      context: .
      dockerfile: signal-server/dockerfile
    ports:
      - 8080:8080