services:
  front:
    build:
      context: .
      dockerfile: front/dockerfile
    ports:
      - 5173:5173
  
  signal-server:
    build: 
      context: .
      dockerfile: signal-server/dockerfile
    ports:
      - 8081:8081