FROM node:16.15.0

WORKDIR /home/ubuntu/app

COPY package.json .
COPY common ./common
COPY signal-server ./signal-server

RUN yarn install

WORKDIR /home/ubuntu/app/signal-server

# RUN npm install --location=global http-server
RUN yarn build

# EXPOSE 3000
# ENTRYPOINT ["http-server", "-c-1", "-p", "3000", "build"]
