FROM node:16.15.0

WORKDIR /home/ubuntu/app

COPY package.json .
COPY common ./common
COPY signal-server ./signal-server

RUN yarn install

WORKDIR /home/ubuntu/app/signal-server

EXPOSE 8080
ENTRYPOINT ["yarn", "start"]